name: Code Style

on:
  push:
    branches:
      - 'v1'
      - 'v2'
      - 'v3'
  pull_request:
    branches:
      - '*'

permissions:
  contents: write

concurrency:
  group: ${{ github.head_ref || github.ref || github.run_id }}_php_cs_fixer
  cancel-in-progress: true

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run PHP CS Fixer
        run: composer run fix-code
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 🪄 Code Style Fixes
