name: Code Style

on:
  push:
    branches:
      - 'v1'
      - 'v2'
      - 'v3'
      - 'v4'
  pull_request:
    branches:
      - '*'

permissions:
  contents: write

concurrency:
  group: ${{ github.head_ref || github.ref || github.run_id }}_php_cs_fixer
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Checkout pull request merge ref
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run PHP CS Fixer
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        run: ./vendor/bin/php-cs-fixer fix --allow-risky=yes

      - name: Check PHP CS Fixer
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository
        run: ./vendor/bin/php-cs-fixer fix --allow-risky=yes --dry-run --diff

      - name: Commit Changes
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 🪄 Code Style Fixes
          commit_options: '--no-verify'
